
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView TextArea;

	private global::Gtk.Entry playerText;

	private global::Gtk.Button CommandButton;

	private global::Gtk.Entry descText;

	private global::Gtk.Entry commandText;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.TextArea = new global::Gtk.TextView();
		this.TextArea.WidthRequest = 308;
		this.TextArea.HeightRequest = 116;
		this.TextArea.CanFocus = true;
		this.TextArea.Name = "TextArea";
		this.TextArea.Editable = false;
		this.TextArea.CursorVisible = false;
		this.GtkScrolledWindow.Add(this.TextArea);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w2.X = 34;
		w2.Y = 25;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.playerText = new global::Gtk.Entry();
		this.playerText.WidthRequest = 235;
		this.playerText.CanFocus = true;
		this.playerText.Name = "playerText";
		this.playerText.IsEditable = true;
		this.playerText.InvisibleChar = '●';
		this.fixed1.Add(this.playerText);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.playerText]));
		w3.X = 33;
		w3.Y = 174;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CommandButton = new global::Gtk.Button();
		this.CommandButton.CanFocus = true;
		this.CommandButton.Name = "CommandButton";
		this.CommandButton.UseUnderline = true;
		this.CommandButton.Label = global::Mono.Unix.Catalog.GetString("Command");
		this.fixed1.Add(this.CommandButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.CommandButton]));
		w4.X = 285;
		w4.Y = 169;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.descText = new global::Gtk.Entry();
		this.descText.WidthRequest = 235;
		this.descText.HeightRequest = 28;
		this.descText.CanFocus = true;
		this.descText.Name = "descText";
		this.descText.IsEditable = true;
		this.descText.InvisibleChar = '●';
		this.fixed1.Add(this.descText);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.descText]));
		w5.X = 35;
		w5.Y = 171;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.commandText = new global::Gtk.Entry();
		this.commandText.WidthRequest = 235;
		this.commandText.CanFocus = true;
		this.commandText.Name = "commandText";
		this.commandText.IsEditable = true;
		this.commandText.InvisibleChar = '●';
		this.fixed1.Add(this.commandText);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.commandText]));
		w6.X = 33;
		w6.Y = 173;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 392;
		this.DefaultHeight = 231;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
